// Generated by CoffeeScript 1.6.2
var app, serverStarted;

app = require("./.espresso");

serverStarted = function() {
  return console.log("Express server listening on http://" + (app.get("ipaddr")) + ":" + (app.get("port")));
};

app.listen(app.get('port'), app.get('ipaddr'), serverStarted);
